[package]
name = "advent-of-code-2023"
version = "0.1.0"
authors = ["Ken Pratt <ken@kenpratt.net>"]
edition = "2021"

[profile.release]
debug = 1

[dependencies]
cached = "0.46.1"
indoc = "2.0.4"
lazy_static = "1.4.0"
