[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["Ken Pratt <ken@kenpratt.net>"]
edition = "2021"

[profile.release]
debug = 1

[dependencies]
lazy_static = "1.4.0"
md5 = "0.7.0"
regex = "1.10.2"
