// generated by build.rs
use crate::template;
use crate::y2015;
use crate::y2018;

pub const YEARS: [usize; 2] = [
    2015,
    2018,
];

pub const DAYS_2015: [usize; 6] = [
    1,
    2,
    3,
    4,
    5,
    6,
];

pub const DAYS_2018: [usize; 13] = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
];

pub fn days_for_year(year: usize) -> &'static [usize] {
    match year {
        2015 => &DAYS_2015,
        2018 => &DAYS_2018,
        _ => panic!("Unknown year: {}", year),
    }
}

pub fn run_fn(year: usize, day: usize) -> Option<fn()> {
    match (year, day) {
        (_, 0) => Some(template::run),
        (2015, 1) => Some(y2015::day_01_not_quite_lisp::run),
        (2015, 2) => Some(y2015::day_02_i_was_told_there_would_be_no_math::run),
        (2015, 3) => Some(y2015::day_03_perfectly_spherical_houses_in_a_vacuum::run),
        (2015, 4) => Some(y2015::day_04_the_ideal_stocking_stuffer::run),
        (2015, 5) => Some(y2015::day_05_doesnt_he_have_intern_elves_for_this::run),
        (2015, 6) => Some(y2015::day_06_probably_a_fire_hazard::run),
        (2018, 1) => Some(y2018::day_01_chronal_calibration::run),
        (2018, 2) => Some(y2018::day_02_inventory_management_system::run),
        (2018, 3) => Some(y2018::day_03_no_matter_how_you_slice_it::run),
        (2018, 4) => Some(y2018::day_04_repose_record::run),
        (2018, 5) => Some(y2018::day_05_alchemical_reduction::run),
        (2018, 6) => Some(y2018::day_06_chronal_coordinates::run),
        (2018, 7) => Some(y2018::day_07_the_sum_of_its_parts::run),
        (2018, 8) => Some(y2018::day_08_memory_maneuver::run),
        (2018, 9) => Some(y2018::day_09_marble_mania::run),
        (2018, 10) => Some(y2018::day_10_the_stars_align::run),
        (2018, 11) => Some(y2018::day_11_chronal_charge::run),
        (2018, 12) => Some(y2018::day_12_subterranean_sustainability::run),
        (2018, 13) => Some(y2018::day_13_mine_cart_madness::run),
        _ => return None,
    }
}
